product7:
  outputs:
    dev:
      account: "KUTQCBB-VF37130"
      database: "domain7_db"
      user: "gb"
      password: "Gau@snowland#1"
      role:  "domain7_engginer"
      schema: "product7"
      threads: 1
      type: snowflake
      warehouse:  "domain7_wh"
  target: dev
